### ISSUE TITLE
can't run,because all dependence are devDependence

### ISSUE THREAD

**Issue by wyknmjj** [sumy7/vite-plugin-generate-file#1]
rt.

please update the npm package

**Comment by sumy7** [comment]
Hi wyknmjj,

This is an vite plugin and needs to be run in the vite environment.

Can you give a simple example to show how to use it?

**Comment by wyknmjj** [comment]
I just edit the package.json,move ejs/js-yaml to depencencies,so i can use.

![image](https://user-images.githubusercontent.com/92901171/144189329-cf3eb7bd-814f-4915-8186-d23fe89da2d9.png)

**Comment by sumy7** [comment]
可以单独编译这个项目，然后使用 `npm link` 将编译后的成品链接到需要的项目中使用。

You can compile this project separately, and then use `npm link` to link the compiled product to the required project.

**Comment by wyknmjj** [comment]
ok

**Comment by wyknmjj** [comment]
![image](https://user-images.githubusercontent.com/92901171/144191971-27972b1f-0723-4d89-b736-7bbd08708f86.png)
because all your dependence are in devDependencies,but the ejs and js-yaml need to be in dependencies.is that true? I use vite and yarn add your package at devDependencies.

**Comment by wyknmjj** [comment]
you can try it in an empty vite project.i use react.very thanks.

**Comment by sumy7** [comment]
我懂你的意思了，我会调整这部分依赖，感谢你的反馈。

I understand what you mean.
I will move `ejs` and `js-yaml` to "dependencies".
Thank you for your feedback.

**Comment by sumy7** [comment]
I publish v0.0.3 and use `yarn create vite my-react-app --template react-ts` to test react vite project.

It looks fine, look forward for your feedback.
