### ISSUE TITLE
Set MIME type of generated file in Dev mode

### ISSUE THREAD

**Issue by geirsagberg-hent** [sumy7/vite-plugin-generate-file#2]
Hi, love your plugin!

I have an issue, where I try to import the JSON file in a script module:

vite.config.ts:
```typescript
...
  generateFile( {
  type   : 'json',
  data   : APP_CONFIG,
  output : 'config.json',
  
  } ),
... 
```

```html
<script type="module">
  import APP_CONFIG from '/config.json' assert { type: 'json' };
  window.APP_CONFIG = APP_CONFIG;
</script>
```

When I run in Dev mode, I get the error:
```
config.json:1 
        
       Failed to load module script: Expected a JSON module script but the server responded with a MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.
```

Would love if the plugin could set correct MIME type based on `json`, or fully configurable, for dev server serving :)

**Comment by sumy7** [comment]
Hi **geirsagberg-hent**,

I'm glad you can use this plugin.

I publish v0.0.4 to support this feature.
You can use new option `ContentType` to specify the response header Content-Type from dev server.
```
...
  generateFile( {
  type   : 'json',
  data   : APP_CONFIG,
  output : 'config.json',
+ contentType: 'application/json',
  } ),
... 

```
if not set this option, plugin will use output extension to guess the MIME type.

This feature is not fully tested, please let me know if you run into any issues.

**Comment by geirsagberg-hent** [comment]
Works perfectly, thanks!
