### ISSUE TITLE
Add new type for plain text content.

### ISSUE THREAD

**Issue by rick-ast** [sumy7/vite-plugin-generate-file#5]
### Issue Type
Feature request
### Description
Could you help to add a new type like `plain` or `text`, since I want to output some plain text without any specific format to a file.
### Expected Configuration
```ts
generateFile([{
  type: 'plain',  // or like 'text' ...
  output: './output',
  data: 'foo bar'
}])

**Comment by sumy7** [comment]
Hi @rick-ast ,
Thank you for your suggestion. Adding a new type like 'plain' or 'text' for outputting plain text without any specific format is an interesting idea. I will consider this for future updates.

In the meantime, you can use ejs `template` to place static text.

```js
generateFile([{
  type: 'template',
  template: './text.ejs',
  output: './output',
}])
```

and in `text.ejs`

```plain
foo bar
```

To better understand how to implement this feature, could you provide more details about your use case?
This information will help me to consider the best approach for this feature.

**Comment by rick-ast** [comment]
> Hi @rick-ast , Thank you for your suggestion. Adding a new type like 'plain' or 'text' for outputting plain text without any specific format is an interesting idea. I will consider this for future updates.
> 
> In the meantime, you can use ejs `template` to place static text.
> 
> ```js
> generateFile([{
>   type: 'template',
>   template: './text.ejs',
>   output: './output',
> }])
> ```
> 
> and in `text.ejs`
> 
> ```
> foo bar
> ```
> 
> To better understand how to implement this feature, could you provide more details about your use case? This information will help me to consider the best approach for this feature.

I may not very clear about that use case, the data would be generated during build time, our system uses micro frontends which needs a version file placed at the same place with static files, and its content is just the build version like 1.2.0 or git hash. So the `data` field in config would be a variable and is not static string. Sorry for the misleading.

**Comment by sumy7** [comment]
> I may not very clear about that use case, the data would be generated during build time, our system uses micro frontends which needs a version file placed at the same place with static files, and its content is just the build version like 1.2.0 or git hash. So the `data` field in config would be a variable and is not static string. Sorry for the misleading.

Hi @rick-ast ,
Based on your description, it appears that EJS can directly render variables. I suggest trying the following code to see if it meets your requirements.

```js
import generateFile from 'vite-plugin-generate-file'
import { defineConfig, loadEnv } from 'vite'

export default defineConfig(({ command, mode }) => {
  const env = loadEnv(mode, process.cwd(), '')
  return {
    server: {
      host: true,
    },
    plugins: [
      generateFile([
        {
          type: 'template',
          template: './version.ejs',
          output: 'latest-version.txt',
          data: {
            version: env.VITE_APP_VERSION,
          },
        },
      ]),
    ],
  }
})
```

and in `version.ejs`

```ejs
<%= version %>
```

the `latest-version.txt` will only show the variable `VITE_APP_VERSION` from `.env` config file.

However, I would still recommend using JSON to store such information. This approach allows you to include more field content in one file, such as version numbers, git hash, and so on.

**Comment by rick-ast** [comment]
> > I may not very clear about that use case, the data would be generated during build time, our system uses micro frontends which needs a version file placed at the same place with static files, and its content is just the build version like 1.2.0 or git hash. So the `data` field in config would be a variable and is not static string. Sorry for the misleading.
> 
> Hi @rick-ast , Based on your description, it appears that EJS can directly render variables. I suggest trying the following code to see if it meets your requirements.
> 
> ```js
> import generateFile from 'vite-plugin-generate-file'
> import { defineConfig, loadEnv } from 'vite'
> 
> export default defineConfig(({ command, mode }) => {
>   const env = loadEnv(mode, process.cwd(), '')
>   return {
>     server: {
>       host: true,
>     },
>     plugins: [
>       generateFile([
>         {
>           type: 'template',
>           template: './version.ejs',
>           output: 'latest-version.txt',
>           data: {
>             version: env.VITE_APP_VERSION,
>           },
>         },
>       ]),
>     ],
>   }
> })
> ```
> 
> and in `version.ejs`
> 
> ```
> <%= version %>
> ```
> 
> the `latest-version.txt` will only show the variable `VITE_APP_VERSION` from `.env` config file.
> 
> However, I would still recommend using JSON to store such information. This approach allows you to include more field content in one file, such as version numbers, git hash, and so on.

It works, thanks. will close this issue
